Update ktlint-git-pre-commit-hook

diff --git a/ktlint-git-pre-commit-hook b/ktlint-git-pre-commit-hook
--- a/ktlint-git-pre-commit-hook
+++ b/ktlint-git-pre-commit-hook
@@ -9,6 +9,11 @@ changed_files=$(git diff --cached --name-only --diff-filter=d | grep "\.kt$")
 # Run ktlint -F on each changed file
 for file in $changed_files; do
   ktlint -F "$file"
+  if [ $? -ne 0 ]; then
+    echo "ktlint check failed, commit denied"
+    git stash pop -q
+    exit 1
+  fi
   git add "$file"
 done
 
